server:
  port: 8080

spring:
  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
  thymeleaf:
    cache: true
  flyway:
    locations: classpath:db/core

  security:
    oauth2:
      client:
        registration:
          oidc:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: openid, email
        provider:
          oidc:
            issuer-uri: ${ISSUER_URI}
